apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 3
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: ${IMAGE_NAME}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              
---
apiVersion: v1 
kind: Service
metadata: 
  name: boardgame-svc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer # type of service.
